In [1]:
import pdfplumber
import pandas as pd
import numpy as np

In [2]:
with pdfplumber.open("../data/raw/ts/account-report-MKI-February-2026.pdf") as pdf:
    print(f"Total Pages in PDF: {len(pdf.pages)}")
    
    page1 = pdf.pages[0]
    lines = page1.extract_text_lines()

    fulltext = page1.extract_table()
    state_name = "unknown"
    month_name = "unknown"
    
    for line in lines:
        text = line["text"]
        
        # 1. Extract State Name
        if "Government of" in text:
            state_parts = text.split("of")
            if len(state_parts) > 1:
                state_name = state_parts[1].split("State")[0].strip()
        
        # 2. Extract Month Name
        # Looking for the line: "Monthly Key Indicators for the month of February 2026"
        if "month of" in text:
            month_parts = text.split("month of")
            if len(month_parts) > 1:
                month_name = month_parts[1].split("2026")[0].strip()
        
        # 3. Stop if both are found
        if state_name != "unknown" and month_name != "unknown":
            break

    # Extracting Table Data
    table_data = page1.extract_table()
    
    print(f"State: {state_name}")
    print(f"Month: {month_name}")

Total Pages in PDF: 9
State: Telangana
Month: February

In [4]:
clean_headers =[
    "Description",
    "Budget Estimates 2025-26",
    "Actuals up to Feb 2026",
    "Percentage: Current 2025-26",
    "Percentage: Corresponding 2024-25"
]

df = pd.DataFrame(fulltext[2:],columns=clean_headers)


df["State"] =state_name
df["month"]=month_name


df.head()

,Description,Budget Estimates 2025-26,Actuals up to Feb 2026,Percentage: Current 2025-26,Percentage: Corresponding 2024-25,State,month
0,1 REVENUE RECEIPTS,229720.63,154346.85,67.19,61.53,Telangana,February
1,a)Tax Revenue,175319.36,139100.81,79.34,75.46,Telangana,February
2,i)Goods and Service Tax,59704.59,48036.72,80.46,79.26,Telangana,February
3,ii)Stamps and Regstration,19087.26,13775.51,72.17,38.58,Telangana,February
4,iii)Land Revenue,11.20,0.54,4.84,7.39,Telangana,February

In [7]:
remove_row = [
    "1 REVENUE RECEIPTS",
    "2 CAPITAL RECEIPTS",
    "a)Tax Revenue",
    "3 TOTAL RECEIPTS",
    "7 TOTAL EXPENDITURE [4+5] (***)"
]
df = df[~df["Description"].isin(remove_row)]

tax_rev_list = [
    "i)Goods and Service Tax",
    "ii)Stamps and Regstration",
    "iii)Land Revenue",
    "iv)Sales Tax",
    "v)State Excise Duties",
    "vi)States Share of Union Taxes (*)",
    "vii)Other Taxes and duties ($)"
    ]

# Use .loc[rows, column] = value
df.loc[df["Description"].isin(tax_rev_list), "cat2"] = "Tax Revenue"

df.loc[~df["Description"].isin(tax_rev_list), "cat2"] = df["Description"].str[2:]

#1 REVENUE RECEIPTS
rev_rec_list =[
    "i)Goods and Service Tax",
    "ii)Stamps and Regstration",
    "iii)Land Revenue",
    "iv)Sales Tax",
    "v)State Excise Duties",
    "vi)States Share of Union Taxes (*)",
    "vii)Other Taxes and duties ($)",
    "b)Non-Tax Revenue",
    "c)Grant in aid and Contributions"
]

df.loc[df["Description"].isin(rev_rec_list),"cat1"] = "REVENUE RECEIPTS"



Cap_rec_list = [
    "a)Recovery of Loans and Advances",
    "b)Other Receipts",
    "c)Borrowings & Other Liabilities (Net ) (**)"
]

df.loc[df["Description"].isin(Cap_rec_list),"cat2"]="Capital Receipts"


print(rev_rec_list)

df=df.reset_index(drop=True)
df.head(50)

['i)Goods and Service Tax', 'ii)Stamps and Regstration', 'iii)Land Revenue', 'iv)Sales Tax', 'v)State Excise Duties', 'vi)States Share of Union Taxes (*)', 'vii)Other Taxes and duties ($)', 'b)Non-Tax Revenue', 'c)Grant in aid and Contributions']

,Description,Budget Estimates 2025-26,Actuals up to Feb 2026,Percentage: Current 2025-26,Percentage: Corresponding 2024-25,State,month,cat2,cat1
0,i)Goods and Service Tax,59704.59,48036.72,80.46,79.26,Telangana,February,Tax Revenue,REVENUE RECEIPTS
1,ii)Stamps and Regstration,19087.26,13775.51,72.17,38.58,Telangana,February,Tax Revenue,REVENUE RECEIPTS
2,iii)Land Revenue,11.20,0.54,4.84,7.39,Telangana,February,Tax Revenue,REVENUE RECEIPTS
3,iv)Sales Tax,37463.90,30628.68,81.76,87.41,Telangana,February,Tax Revenue,REVENUE RECEIPTS
4,v)State Excise Duties,27623.36,20454.14,74.05,65.61,Telangana,February,Tax Revenue,REVENUE RECEIPTS
5,vi)States Share of Union Taxes (*),21195.18,18788.79,88.65,93.79,Telangana,February,Tax Revenue,REVENUE RECEIPTS
6,vii)Other Taxes and duties ($),10233.87,7416.43,72.47,72.10,Telangana,February,Tax Revenue,REVENUE RECEIPTS
7,b)Non-Tax Revenue,31618.77,9105.39,28.80,17.25,Telangana,February,Non-Tax Revenue,REVENUE RECEIPTS
8,c)Grant in aid and Contributions,22782.50,6140.65,26.95,27.78,Telangana,February,Grant in aid and Contributions,REVENUE RECEIPTS
9,a)Recovery of Loans and Advances,1106.93,42.53,3.84,1.11,Telangana,February,Capital Receipts,NaN
10,b)Other Receipts,0.00,0.00,0.00,0.00,Telangana,February,Capital Receipts,NaN
11,c)Borrowings & Other Liabilities (Net ) (**),54009.74,77111.10,142.77,130.86,Telangana,February,Capital Receipts,NaN
12,4 Revenue Expenditure (a+b+c+d+e),226982.28,168711.46,74.33,74.35,Telangana,February,Revenue Expenditure (a+b+c+d+e),NaN
13,(a)Expenditure on Revenue Account (excluding b...,133440.77,67745.29,50.77,56.17,Telangana,February,")Expenditure on Revenue Account (excluding b,c...",NaN
14,(b)Expenditure in Interest Payments,19369.02,26218.45,135.36,135.81,Telangana,February,)Expenditure in Interest Payments,NaN
15,(c)Expenditure on Salaries/Wages,44478.87,43457.52,97.70,97.30,Telangana,February,)Expenditure on Salaries/Wages,NaN
16,(d)Expenditure on Pension,13109.67,17568.65,134.01,132.98,Telangana,February,)Expenditure on Pension,NaN
17,(e)Expenditure on Subsidy,16583.95,13721.55,82.74,59.21,Telangana,February,)Expenditure on Subsidy,NaN
18,5 Capital Expenditure (a+b+c),36504.45,48432.10,132.67,97.94,Telangana,February,Capital Expenditure (a+b+c),NaN
19,(a)Expenditute on Capital Account (excluding b),35700.28,47556.98,133.21,97.58,Telangana,February,)Expenditute on Capital Account (excluding b),NaN
20,(b)Expenditure on Salaries/Wages,804.17,875.12,108.82,100.26,Telangana,February,)Expenditure on Salaries/Wages,NaN
21,(c)Inter State Settlement (Net),0.00,0.00,0.00,0.00,Telangana,February,)Inter State Settlement (Net),NaN
22,6 Sector wise Expediture (i+ii+iii+iv) (***),263486.74,217143.55,82.41,77.41,Telangana,February,Sector wise Expediture (i+ii+iii+iv) (***),NaN
23,(i)General Sector,50173.21,63047.16,125.66,117.33,Telangana,February,)General Sector,NaN
24,a)Revenue,48283.69,62333.28,129.10,121.97,Telangana,February,Revenue,NaN
25,b)Capital,1889.52,713.88,37.78,21.16,Telangana,February,Capital,NaN
26,(ii)Social Sector,121469.97,75005.88,61.75,60.48,Telangana,February,i)Social Sector,NaN
27,a)Revenue,110966.66,66550.67,59.97,59.91,Telangana,February,Revenue,NaN
28,b)Capital,10503.31,8455.21,80.50,66.15,Telangana,February,Capital,NaN
29,(iii)Economic Sector,91833.46,79090.51,86.12,76.25,Telangana,February,ii)Economic Sector,NaN
30,a)Revenue,67721.84,39827.51,58.81,65.45,Telangana,February,Revenue,NaN
31,b)Capital,24111.62,39263.00,162.84,118.12,Telangana,February,Capital,NaN
32,(iv)Grant in aid and Contributions,10.10,0.00,0.00,0.00,Telangana,February,v)Grant in aid and Contributions,NaN
33,8 LOANS AND ADVANCES DISBURSED,21350.55,14356.92,67.24,18.17,Telangana,February,LOANS AND ADVANCES DISBURSED,NaN
34,9 Revenue Surplus/Deficit [1-4],2738.35,-14364.61,-524.57,-9459.10,Telangana,February,Revenue Surplus/Deficit [1-4],NaN
35,10 Fiscal Deficit [1+2(a)+(b)] -(7+8),-54009.72,-77111.10,142.77,130.66,Telangana,February,Fiscal Deficit [1+2(a)+(b)] -(7+8),NaN
36,11 Primary Surplus/Deficit [1+2(a)+2(b)]-[4(a+...,-34640.70,-50892.65,146.92,128.08,Telangana,February,Primary Surplus/Deficit [1+2(a)+2(b)]-[4(a+c+...,NaN